### ISSUE TITLE
部署服务时遇到了问题

### ISSUE THREAD

**Issue by wgsxsm** [zhangyile/telegram-wechat#1]
# 拉取仓库代码--完成
# 修改 config.py 文件，填入 Token 和 ID--完成

以下两步均有提示
# 启动服务
docker compose up -d 
提示如下：
unknown shorthand flag: 'd' in -d
See 'docker --help'.
# 查看日志中的微信二维码，扫码登录
docker compose logs -f
提示如下：
unknown shorthand flag: 'f' in -f
See 'docker --help'.

感觉是不是跳了什么步骤？

**Comment by zhangyile** [comment]
看报错，你这应该是只安装了 docker，没有安装 docker compose 吧，文档里是用 docker compose 去部署的。你把docker compose 装上应该就好了，以后我再加一个 docker 部署的步骤。

**Comment by zhangyile** [comment]
可以执行 `docker-compose --version` 或 `docker compose version` 来确认是否已经安装了 docker compose.

**Comment by wgsxsm** [comment]
谢谢提醒 原来是要执行docker-compose up -d
