### ISSUE TITLE
`/update_info`无效

### ISSUE THREAD

**Issue by imldy** [zhangyile/telegram-wechat#2]
已将此联系人**单独绑定**到TG群聊，已将Bot设置为群聊管理员，但是在群聊发送`/update_info@myWeChatBot`无效，且`docker-compose logs -f`无新增输出。重新link同样如此。

查阅[efb-telegram-master官方资料](https://github.com/ehForwarderBot/efb-telegram-master/blob/master/readme_translations/zh_CN.rst#update_info%E6%9B%B4%E6%96%B0%E8%A2%AB%E7%BB%91%E5%AE%9Atelegram%E7%BE%A4%E7%B5%84%E7%9A%84%E8%AF%A6%E6%83%85%E4%BF%A1%E6%81%AF)

描述为：
>/update_info：更新被绑定 Telegram 群組的详情信息
ETM 可以协助您依照远端会话来更新 Telegram 群组的名称和头像。如果远端会话是一个群组，ETM 还可以将群组的成员列表写入 Telegram 会话的简介中。

>此功能仅在满足以下条件的情况下可用：
> * 该命令发送于群组
> * Bot 是该群组的管理员。
> * 该群组[**](https://github.com/ehForwarderBot/efb-telegram-master/blob/master/readme_translations/zh_CN.rst#id15)仅绑定到了一个**远端会话
> * 远端会话当前可用

> 
>从端如果没有提供会话的头像，群组的头像将不会被改变。

满足这四个条件，但是没有反应，请问是从端代码的问题吗？

**Comment by zhangyile** [comment]
你好，这个应该是从端代码的问题，需要去找原作者哈，我只是个搬运工。0.0
