### ISSUE TITLE
没有二维码

### ISSUE THREAD

**Issue by chairezj998** [zhangyile/telegram-wechat#4]
在执行docker compose logs -f命令后得到以下信息，没有二维码出现，不知道哪里错了

telegram-wechat-telegram-wechat-1  | 07-02-2023:05:37:11,793 CRITICAL [main.py:83]
telegram-wechat-telegram-wechat-1  |       Initializing slave ('plugins.eh_wechat_slave', 'WeChatChannel')...
telegram-wechat-telegram-wechat-1  | 07-02-2023:05:37:37,631 ERROR    [utils.py:138]
telegram-wechat-telegram-wechat-1  |      Traceback (most recent call last):
telegram-wechat-telegram-wechat-1  |   File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
telegram-wechat-telegram-wechat-1  |     (self.host, self.port), self.timeout, **extra_kw)telegram-wechat-telegram-wechat-1  |   File "/usr/lib/python3.6/site-packages/urllib3/util/connection.py", line 60, in create_connection
telegram-wechat-telegram-wechat-1  |     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
telegram-wechat-telegram-wechat-1  |   File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
telegram-wechat-telegram-wechat-1  |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
telegram-wechat-telegram-wechat-1  | socket.gaierror: [Errno -3] Try again
telegram-wechat-telegram-wechat-1  |
telegram-wechat-telegram-wechat-1  | During handling of the above exception, another exception occurred:
telegram-wechat-telegram-wechat-1  |
telegram-wechat-telegram-wechat-1  | Traceback (most recent call last):
telegram-wechat-telegram-wechat-1  |   File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
telegram-wechat-telegram-wechat-1  |     chunked=chunked)
telegram-wechat-telegram-wechat-1  |   File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 346, in _make_request
telegram-wechat-telegram-wechat-1  |     self._validate_conn(conn)
telegram-wechat-telegram-wechat-1  |   File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
telegram-wechat-telegram-wechat-1  |     conn.connect()
telegram-wechat-telegram-wechat-1  |   File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 284, in connect
telegram-wechat-telegram-wechat-1  |     conn = self._new_conn()
telegram-wechat-telegram-wechat-1  |   File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
telegram-wechat-telegram-wechat-1  |     self, "Failed to establish a new connection: %s" % e)
telegram-wechat-telegram-wechat-1  | urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f882dc105c0>: Failed to establish a new connection: [Errno -3] Try again
telegram-wechat-telegram-wechat-1  |
telegram-wechat-telegram-wechat-1  | During handling of the above exception, another exception occurred:
telegram-wechat-telegram-wechat-1  |
telegram-wechat-telegram-wechat-1  | Traceback (most recent call last):
telegram-wechat-telegram-wechat-1  |   File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
telegram-wechat-telegram-wechat-1  |     timeout=timeout
telegram-wechat-telegram-wechat-1  |   File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
telegram-wechat-telegram-wechat-1  |     _stacktrace=sys.exc_info()[2])
telegram-wechat-telegram-wechat-1  |   File "/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
telegram-wechat-telegram-wechat-1  |     raise MaxRetryError(_pool, url, error or ResponseError(cause))
telegram-wechat-telegram-wechat-1  | urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='login.weixin.qq.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f882dc105c0>: Failed to establish a new connection: [Errno -3] Try again',))
telegram-wechat-telegram-wechat-1  |
telegram-wechat-telegram-wechat-1  | During handling of the above exception, another exception occurred:
telegram-wechat-telegram-wechat-1  |
telegram-wechat-telegram-wechat-1  | Traceback (most recent call last):
telegram-wechat-telegram-wechat-1  |   File "/usr/lib/python3.6/site-packages/itchat/utils.py", line 134, in test_connect
telegram-wechat-telegram-wechat-1  |     r = requests.get(config.BASE_URL)
telegram-wechat-telegram-wechat-1  |   File "/usr/lib/python3.6/site-packages/requests/api.py", line 72, in get
telegram-wechat-telegram-wechat-1  |     return request('get', url, params=params, **kwargs)
telegram-wechat-telegram-wechat-1  |   File "/usr/lib/python3.6/site-packages/requests/api.py", line 58, in request
telegram-wechat-telegram-wechat-1  |     return session.request(method=method, url=url, **kwargs)
telegram-wechat-telegram-wechat-1  |   File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
telegram-wechat-telegram-wechat-1  |     resp = self.send(prep, **send_kwargs)
telegram-wechat-telegram-wechat-1  |   File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
telegram-wechat-telegram-wechat-1  |     r = adapter.send(request, **kwargs)
telegram-wechat-telegram-wechat-1  |   File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 508, in send
telegram-wechat-telegram-wechat-1  |     raise ConnectionError(e, request=request)
telegram-wechat-telegram-wechat-1  | requests.exceptions.ConnectionError: HTTPSConnectionPool(host='login.weixin.qq.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f882dc105c0>: Failed to establish a new connection: [Errno -3] Try again',))
telegram-wechat-telegram-wechat-1  |
telegram-wechat-telegram-wechat-1 exited with code 0

**Comment by zhangyile** [comment]
看报错应该是和 login.weixin.qq.com:443 网络不通

**Comment by chairezj998** [comment]
有什么解决办法吗😭

**Comment by chairezj998** [comment]
> 看报错应该是和 login.weixin.qq.com:443 网络不通

那有什么解决办法吗？😭

**Comment by zhangyile** [comment]
网络不通，就先解决网络问题，可以在服务器上执行一下 `ping login.weixin.qq.com`，看看通没通，或者执行 `nc login.weixin.qq.com 443 -v` 看看输出

**Comment by chairezj998** [comment]
> 网络不通，就先解决网络问题，可以在服务器上执行一下 `ping login.weixin.qq.com`，看看通没通，或者执行 `nc login.weixin.qq.com 443 -v` 看看输出

执行ping login.weixin.qq.com输出
PING wx1.qq.com (43.129.255.96) 56(84) bytes of data.后就没反应了
执行nc login.weixin.qq.com 443 -v 输出
Ncat: Version 7.50 ( https://nmap.org/ncat )
Ncat: Connected to 240e:e1:a802:1::1c:443.
后续也一直不动，没有新的输出
两个命令执行了几次都这样

**Comment by zhangyile** [comment]
Ncat: Connected to 240e:e1:a802:1::1c:443.
========
有这行说明网络是通的。
那这个具体什么问题就不好排查了。

**Comment by chairezj998** [comment]
好的，谢谢解答，我再看看

**Comment by chairezj998** [comment]
https://blog.csdn.net/a1007720052/article/details/83383220
我网上搜到一些相似的例子，里面的解决方法好像是要修改文件内容，但我没有在文件里找到相似的地方，可以麻烦您告诉一下在哪里吗

**Comment by zhangyile** [comment]
你搜的那个报错和你实际的报错不一样，两个不是一回事，我猜可能是 ipv6 导致的。
你修改一下你服务器上的 /etc/hosts 文件，加一行 ` login.weixin.qq.com 43.129.255.96` 进去，然后再重新部署一下试试？

**Comment by zhangyile** [comment]
> https://blog.csdn.net/a1007720052/article/details/83383220 我网上搜到一些相似的例子，里面的解决方法好像是要修改文件内容，但我没有在文件里找到相似的地方，可以麻烦您告诉一下在哪里吗

你搜的那个报错和你实际的报错不一样，两个不是一回事，我猜可能是 ipv6 导致的。
你修改一下你服务器上的 /etc/hosts 文件，加一行 `43.129.255.96 login.weixin.qq.com`  进去，然后再重新部署一下试试？

**Comment by chairezj998** [comment]
> 你修改一下你服务器上的 /etc/hosts 文件，加一行 `43.129.255.96 login.weixin.qq.com` 进去，然后再重新部署一下试试？

服务器是纯ipv6，host文件原来没有，我`vim /etc/host` 显示新文件，那行添加进去了，重新部署我整个服务器重装重新来了一遍，还是报错

**Comment by zhangyile** [comment]
😂那就真晓不得了。
