### ISSUE TITLE
“外挂”警告怎么避免？

### ISSUE THREAD

**Issue by wgsxsm** [zhangyile/telegram-wechat#5]
不知道是不是 /update_info命令被我连续执行了多次之后，没过多久，微信被强制退出，并提示“因使用了微信外挂、非官方客户端或模拟器，被临时限制登录，请尽快卸载对应的非法软件。”
再整出一个备用微信号之前，暂时不敢登录了。
有没有办法搞定这种风险警告？

**Comment by BeyondIM** [comment]
遇到同样的问题，提示外挂，并且微信把服务器 IP 封了

**Comment by wgsxsm** [comment]
> 遇到同样的问题，提示外挂，并且微信把服务器 IP 封了

还能再继续使用不？这种警告有没有次数？

**Comment by zhangyile** [comment]
我的也用不了了，提示外挂，被临时封禁了。八成是微信官方封了 itchat-uos 的登录方式。
